MVCEveining/Controllers/DataController.cs
using MVCEveining.Helpers;
using MVCEveining.Models;
using MVCEveining.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEveining.Controllers
{
    public class DataController : Controller
    {

        Repository repository = new Repository();

        [PermissionRequired(MVCEveining.ViewModels.LoginForm.Permissions.RegisterCustomers)]
        public ActionResult Create()
        {
            //ViewBag.myListJoin = repository.GetListJoin();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Person personClass)
        {
            if (ModelState.IsValid)
            {
                repository.Create(personClass);
                TempData["SuccessMessage"] = "Successfully Saved";
                return RedirectToAction("Create");
            }
            return View();
        }





        public ActionResult Picture(string ID)
        {
            var pic = repository.Getimage1(ID);
            return File(pic, "image/jpeg");
        }

        //public ActionResult List()
        //{
        //     var myList = repository.GetList();
        //    // var myListJoin = repository.GetListJoin();

        //   // ViewBag.myListJoin = repository.GetListJoin();
        //    return View(myList);
        //}


        [PermissionRequired(MVCEveining.ViewModels.LoginForm.Permissions.CustomersLst)]
        public ActionResult MyList(string searchTerm)
        {
            var myList = repository.GetList(searchTerm: searchTerm);
            return View(myList);
        }

        //public ActionResult MyList(string searchTerm)
        //{
        //    var myList = repository.GetList(searchTerm: searchTerm);
        //    return  PartialView("_PeopleList",myList);
        //}

        [PermissionRequired(MVCEveining.ViewModels.LoginForm.Permissions.Update)]
        public ActionResult Edit(string ID)
        {
            var myList = repository.GetListForUpdate(ID);
            return View(myList);
        }
        [PermissionRequired(MVCEveining.ViewModels.LoginForm.Permissions.Update)]
        [HttpPost]
        public ActionResult Edit(Person update)
        {
            {
                repository.Update(update);
                TempData["Success"] = "Successfully Updated";
                return RedirectToAction("Edit");

            }
            return View();
        }

        [PermissionRequired(MVCEveining.ViewModels.LoginForm.Permissions.Delete)]
        public ActionResult Delete(string ID)
        {
            var myList = repository.GetListForUpdate(ID);
            return View(myList);
        }
        [PermissionRequired(MVCEveining.ViewModels.LoginForm.Permissions.Delete)]
        [HttpPost]
        public ActionResult Delete(Person delete)
        {
            repository.Delete(delete);
            // TempData["Success"] = "Successfully Updated";
            return RedirectToAction("Delete");
        }


        public ActionResult testtt()
        {
            return View();
        }
    }
}

MVCEveining/Views/Shared/Unauthorized.cshtml

@{
    ViewBag.Title = "Unauthorized";
}

<body>
    <ul class="breadcrumb push-down-0">
        <li><a href="#">Home</a></li>
        <li><a href="#">Pages</a></li>
        <li class="active">UnAuthorized</li>
    </ul>
    <!-- END BREADCRUMB -->
    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">
        <div class="row">
            <div class="col-md-12">
                <div class="error-container">
                    <div class="error-code">UnAuthorized</div>
                    <div class="error-text">You don't have the permissions to access this page.</div>
                </div>
            </div>
        </div>
    </div>
    <!-- END PAGE CONTENT WRAPPER -->
    <!-- END PAGE CONTAINER -->
    <!-- MESSAGE BOX-->
</body>





MVCEveining/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")




    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li><a href="~/Main/Index">My Link</a></li>
                    <li>@Html.ActionLink("Create", "Create", "Data")</li>

                    <li>@Html.ActionLink("People List", "MyList", "Data")</li>
                    <li> <a href="~/Authentication/Logout"> <i class="fa fa-sign-out"></i>Logout</a></li>
                </ul>
            </div>
        </div>


    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>